sylius_grid:
    grids:
        sylius_admin_product:
            fields:
                isOnSale:
                    label: 'sylius.admin.product.is_on_sale'
                    type: twig
                    options:
                        template: '@SyliusUi/Grid/Field/yesNo.html.twig'
