sylius_grid:
    grids:
        sylius_admin_product:
            fields:
                isOnSale:
                    label: 'sylius.admin.product.is_on_sale'
                    type: twig
                    options:
                        template: '@SyliusUi/Grid/Field/yesNo.html.twig'
        app_admin_term:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Term\Term
            fields:
                code:
                    type: string
                    label: sylius.ui.code
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
